export const C = {
  bg: '#060606',
  surface: '#0f0f0f',
  surface2: '#171717',
  surface3: '#1f1f1f',
  border: '#272727',
  borderGold: '#3a2e10',
  gold: '#c9a435',
  goldLight: '#e8c96f',
  goldDim: '#6a5418',
  goldGlow: 'rgba(201,164,53,0.12)',
  text: '#f0f0f0',
  textSub: '#aaaaaa',
  textMuted: '#555555',
  white: '#ffffff',
  red: '#e05555',
  green: '#4caf72',
} as const;

export const FONT = {
  serif: "'DM Serif Display', serif",
  sans: "'Inter', sans-serif",
} as const;

export const SLICE_COLORS = [
  '#c9a435',
  '#4a8fd4',
  '#9b59b6',
  '#2ecc71',
  '#e74c3c',
  '#1abc9c',
  '#f39c12',
  '#3498db',
  '#e91e63',
  '#00bcd4',
  '#ff5722',
  '#8bc34a',
  '#673ab7',
  '#ff9800',
  '#009688',
  '#607d8b',
] as const;

export const GEO_COLORS: Record<string, string> = {
  'United States': '#4a8fd4',
  China: '#e74c3c',
  India: '#f39c12',
  Europe: '#2ecc71',
  Japan: '#e91e63',
  'United Kingdom': '#9b59b6',
  'Emerging Markets': '#1abc9c',
  Global: '#c9a435',
  'Asia-Pacific': '#ff9800',
  Taiwan: '#00bcd4',
  'South Africa': '#8bc34a',
  Brazil: '#ff5722',
  Canada: '#607d8b',
  'Middle East': '#673ab7',
  'Southeast Asia': '#3498db',
  Australia: '#27ae60',
};

export const REGIONS = [
  { id: 'global', label: 'Global (All)', group: 'Global' },
  { id: 'us', label: 'United States', group: 'Americas' },
  { id: 'canada', label: 'Canada', group: 'Americas' },
  { id: 'brazil', label: 'Brazil', group: 'Americas' },
  { id: 'latin_america', label: 'Latin America', group: 'Americas' },
  { id: 'uk', label: 'United Kingdom', group: 'Europe' },
  { id: 'germany', label: 'Germany', group: 'Europe' },
  { id: 'france', label: 'France', group: 'Europe' },
  { id: 'europe', label: 'Europe (Broad)', group: 'Europe' },
  { id: 'china', label: 'China', group: 'Asia-Pacific' },
  { id: 'japan', label: 'Japan', group: 'Asia-Pacific' },
  { id: 'india', label: 'India', group: 'Asia-Pacific' },
  { id: 'south_korea', label: 'South Korea', group: 'Asia-Pacific' },
  { id: 'australia', label: 'Australia', group: 'Asia-Pacific' },
  { id: 'southeast_asia', label: 'Southeast Asia', group: 'Asia-Pacific' },
  { id: 'south_africa', label: 'South Africa', group: 'Africa & Middle East' },
  { id: 'nigeria', label: 'Nigeria', group: 'Africa & Middle East' },
  { id: 'africa', label: 'Africa (Broad)', group: 'Africa & Middle East' },
  { id: 'middle_east', label: 'Middle East', group: 'Africa & Middle East' },
  { id: 'emerging_markets', label: 'Emerging Markets', group: 'Thematic' },
  { id: 'frontier_markets', label: 'Frontier Markets', group: 'Thematic' },
  { id: 'commodities', label: 'Commodities', group: 'Thematic' },
] as const;

export const HOME_COUNTRIES = [
  { value: 'us', label: 'United States (USD)', currency: 'USD', symbol: '$' },
  { value: 'uk', label: 'United Kingdom (GBP)', currency: 'GBP', symbol: '£' },
  { value: 'eu', label: 'European Union (EUR)', currency: 'EUR', symbol: '€' },
  { value: 'za', label: 'South Africa (ZAR)', currency: 'ZAR', symbol: 'R' },
  { value: 'au', label: 'Australia (AUD)', currency: 'AUD', symbol: 'A$' },
  { value: 'ca', label: 'Canada (CAD)', currency: 'CAD', symbol: 'C$' },
  { value: 'jp', label: 'Japan (JPY)', currency: 'JPY', symbol: '¥' },
  { value: 'in', label: 'India (INR)', currency: 'INR', symbol: '₹' },
  { value: 'cn', label: 'China (CNY)', currency: 'CNY', symbol: '¥' },
  { value: 'br', label: 'Brazil (BRL)', currency: 'BRL', symbol: 'R$' },
  { value: 'ng', label: 'Nigeria (NGN)', currency: 'NGN', symbol: '₦' },
  { value: 'other', label: 'Other', currency: 'USD', symbol: '$' },
] as const;

export const DURATIONS = [
  { value: '1', label: '1 year' },
  { value: '2-3', label: '2-3 years' },
  { value: '5', label: '5 years' },
  { value: '10', label: '10 years' },
  { value: '10+', label: 'More than 10 years' },
  { value: 'indefinite', label: 'Indefinitely' },
] as const;
